### PR TITLE
Fixes #113: cors config was causing jboss to bounce all the time

### LINKED ISSUE #113: Puppet is restarting jboss frequently when things shouldn't be changing
Make it stop...

### PR DESCRIPTION
**Pull request by jewzaam**
* moved notify jbossas to the file inside cors configuration class
* changed default owner/group for cors config from 'root' to 'jboss'
* some lint fixes

Note that the first thing, moving the notify, probably has no effect.  But I liked it moved to one place so I'm proposing we keep it.

### CODE REVIEW

**Comment by alechenninger** [comment]
So what was happening that was causing the config to bounce jboss all the time?

And sorry about that, by the way :).

**Comment by dcrissman** [comment]
I am not familiar with jboss and "cors". Is it intended that these files would change often?

**Comment by luan-cestari** [comment]
@jewzaam The build failed. I think it is something due the double quote change on the lightblue::service::cors::configure . After it successfully build, I will be happy to merge it

**Comment by jewzaam** [comment]
@alechenninger it was the owner/group for the files.  They were being reset to 'root' every  puppet run which notifies jbossas service.  They can be owned by jboss.

@luan-cestari there is a unit test that I forgot to update.  I'll push a change soon that hopefully will work.  I can't run the tests locally so we'll see what travis says.

**Comment by jewzaam** [comment]
@dcrissman no

**Comment by luan-cestari** [comment]
@jewzaam the build failed . I will move it to in_progress

**Comment by jewzaam** [comment]
Fixed issue in the test for this PR but it's failing in application/datamgmt_spec now.
@alechenninger any chance you know why?

**Comment by dcrissman** [comment]
@jewzaam @alechenninger I noticed other PRs are failing for similar reasons, so I just rebuilt the master branch, and it has the same problems now with ruby 1.8.7. It was all green lights before, so I am guessing a change made to travis itself?

**Comment by dcrissman** [comment]
Please merge in changes from master and re-run tests.

**Comment by dcrissman** [comment]
@jewzaam I see this is marked as in progress, is that still true or is this ready for review?

**Comment by jewzaam** [comment]
@dcrissman yes, updated labels

**Comment by jewzaam** [comment]
err, I should read closer.  "yes" meaning yes ready for review.. thanks!

**Pull request merged**
