### PR TITLE
Fixes how truststore is deployed

### PR DESCRIPTION
**Pull request by jewzaam**
Removes lightblue::cacert class.  It was just used to land the identity cert which is then pulled into the truststore (eap6trust.keystore).  It conflicted with other internal puppet classes and this cleans it up and gets that identity cert loaded correctly in the container.

### CODE REVIEW

**Comment by dcrissman** [comment]
Merge in changes from master. Should address the false errors.

**Comment by jewzaam** [comment]
merged

**Comment by dcrissman** [comment]
The remaining error looks legit.

**Comment by jewzaam** [comment]
@dcrissman fixed the issues finally, tests pass

**Pull request merged**
