### PR TITLE
Add support for enabling/configuring CORS via Hiera (fixes #82)

### LINKED ISSUE #82: Fixes #83: Add support for CORS configuration
See: https://github.com/lightblue-platform/lightblue-rest/pull/86

Need to lay down a templated config file much like the other crud and metadata config files.

I can work on this tomorrow.

### PR DESCRIPTION
**Pull request by alechenninger**
Woooooow if it weren't for rspec-puppet this would've taken a week to do. :)

### CODE REVIEW

**Comment by alechenninger** [comment]
No idea why those tests are failing on the PR build. I didn't touch anything with the migrator.

**Comment by jewzaam** [comment]
Given the configuration input is a hash please provide documentation in each puppet class.
Why have a single template for each cors configuration?  Two reasons I would consider dropping it.  First is it adds another layer of puppet stuff.  Second, it requires metadata and data configuration to evolve in lock step.  While this is probably ok, it seems we could decouple the two and simplify things now by just providing two templates.

**Comment by alechenninger** [comment]
Hrm. I'm not sure I see why they should be two templates. To me that sounds like duplication. In rest there is only one configuration class -- metadata and data are not separate, so any changes would have to be made in both templates unless that was refactored as well. I could see more domain specific configuration perhaps one day (like, find and insert are allowed cross origin but not save and update, as opposed to request methods and URL patterns), but I would lean towards refactoring that when the time comes, if ever.

The other thing I like about having the file as a single separate define resource is anyone using a different container can use it, it is flexible. Should I copy this and have two define resources, data and metadata cors config? That would be still more layers of puppet stuff.

I could see getting rid of the data and metadata cors classes, and instead including the cors config resource directly in module.pp (for each data and metadata), but keeping the single template and associated define resource. This would kill a puppet layer without adding duplication. What do you think?

**Comment by jewzaam** [comment]
Then let's remove the cors class and use the template directly.  One problem I have with it is that it's off on its own.  There's no clear sense of where it lives in the class structure.  Maybe if it were moved it would be better, but it could just go away as well.

**Comment by alechenninger** [comment]
I dig it. Thank you very much for the feedback. Will update today.

**Pull request merged**
