### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by dcrissman**
fix a couple of small things

### CODE REVIEW

**Comment by jewzaam** [comment]
How did you find this as an issue?  I don't see test changes, was there nothing to verify the change worked?

**Comment by jewzaam** [comment]
Sorry, specifically curious about the change to serviceJvmOptions

**Comment by dcrissman** [comment]
These were fixes found while working on #122. serviceJvmOptions should have always been an array, it was mistakenly set to default to an empty hash.

**Comment by dcrissman** [comment]
@jewzaam to append to my last update, see: https://github.com/lightblue-platform/lightblue-puppet/blob/master/manifests/application/migrator/daemon.pp#L49

**Pull request merged**
